### ISSUE TITLE
Study Group Planner

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#19]
We are working on planning sessions for the remainder of this fall and for next spring. The agenda is still very much in draft form, so any input is very much appreciated. 
## Spring 2016 (draft)

| Week of | Date | Session | Trainer |
| --- | --- | --- | --- |
| Jan. 11 | N/A | Winter Break | N/A |
| Jan. 18 | Jan 21 | Hacky Hour - BU Pub | Tom |
| Jan. 25 | Jan 27 | Intro to GitHub | Alexey |
| Feb. 1 | Feb 4 (?) | Using Jupyter | Mark |
| Feb. 8 | Feb 11 | Git Advanced | Alexey |
| Feb. 15 | Feb 18 | Vagrant | Chris |
| Feb. 22 | Feb 25 | Using Jekyll for Publishing | Tom |
| Feb. 29 | Mar 3 | Docker | Chris |
| Mar. 7 | N/A | Spring Break - No Session |  |
| Mar. 14 | Mar 17 | Reveal.js | Chris |
| Mar. 21 | Mar 24 | R Shiny | istfer |
| Mar. 28 | Mar 31 | Julia | Will |
| Apr. 4 | Apr 7 | Coworking Session | Tom |
| Apr. 11 | Apr 14 | OPEN |  |
| Apr. 18 | Apr 21 | Coworking Session - Lightning Talk Prep & Assessment | Tom |
| Apr. 25 | Apr 28 | Lightning Talk Session | Tom (coordinate) |
| May 1 | May 5 | Hacky Hour |  |

**Comment by ceholden** [comment]
The rest of this year looks well booked up (yay!) and I agree that we should repeat some of our content in the new year. Hoping we'll have some new faces joining the familiar ones.

As for additional content, I'd like to propose:
1. Work along for [reveal.js](https://github.com/hakimel/reveal.js) HTML based slides
   - I quite like `reveal.js` since it makes it very quick to create a presentation that looks reasonably good. There isn't a lot of control on styling, which means you're pretty much forced into concise slides that favor images over text
   - You can write HTML to make the slides, but I'd also show how to write the slides in Markdown and then use [pandoc](http://pandoc.org/) to convert them to reveal.js HTML or other formats (Beamer, other HTML slide formats, etc.)
2. Work along for programatically building virtual machine (VM) images to encapsulate your software for distribution or testing using [Vagrant](https://www.vagrantup.com/)
   - I've found it very useful to distribute VMs that contain some of my software with large lists of dependencies, especially for Windows users who don't have access to or know how to setup a compiler. I need to learn it anyway, so I might as well make a lesson on it
3. Work along demonstrating the utility of Makefiles for data processing
   - Like science? You should like reproducible research. Makefiles provide a nice, albeit initially frustrating due to syntax, way of completely documenting the steps in a data analysis workflow
   - Why not just [let Mike Bostock speak for me](http://bost.ocks.org/mike/make/)...
   - I've also recently stumbled upon a "Makefile for data" program called [Drake](https://github.com/Factual/drake)
     - Looks like it has lesson confusing syntax!
     - Can generate workflow dependency graphs
     - See [their blog post](https://www.factual.com/blog/introducing-drake-a-kind-of-make-for-data)

**Comment by tomhohenstein** [comment]
@ceholden great ideas! do you have a preference for dates? We could do the reveal.js session after the git advanced and the Vagrant after the break. Thoughts?

**Comment by ceholden** [comment]
@tomhohenstein I don't have any plans for the dates scheduled right now, so put me where ever and I'll speak up if I need to reschedule? There's some possible work related travel currently up in the air for the spring...

I also want to add another proposed lesson -- Makefiles for data

**Comment by tomhohenstein** [comment]
semester is almost over and each session was added in a respective issues - closing issue
