### ISSUE TITLE
Adding submodules 

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#21]
@ceholden proposed adding a submodule for reveal.js and potentially other git repos - like jekyll - in his pull request for the jupyter lesson. We decided to open the conversation in a new issue. 

The current list of pros / cons: 
**Pros**
- All documentation in one spot 
- Documentation should keep pace with the other projects as they move forward. 

**Cons**
- A little more complex to handle in git (however, we could take advantage of the wiki to document how to do this currently)

**Comment by ashiklom** [comment]
I really like the idea of submodules. That way, I can build my tutorials, etc. in my own repositories that can be incorporated into my fancy shmancy GitHub.io page (thanks @tomhohenstein for the fantastic tutorial!).

That said, there is some weirdness with submodules that I haven't fully been able to figure out yet, so it would be nice to have a tutorial (or co-working session) on using them properly. If you need volunteers, I can take the lead on that since I have some experience working with them and it would a good opportunity to learn more.

**Comment by ceholden** [comment]
I'm also in favor of adding in general purpose utilities like `reveal.js` in as submodules into the root of this repository because it's a simple enough feature addition.

I used to use a submodule that linked two of my projects, `TSTools` and `yatsm`, together, but that situation was too complicated to manage using submodules and I've since discontinued the usage in the `TSTools` project. 

I thought this discussion on HackerNews about submodules is worth reading (be sure to read the original post linked at the top!):
https://news.ycombinator.com/item?id=3904932

I share the opinion of user "buddydvd" (can't seem to permalink to his comment), which is that using submodules is usually worth any downsides. The main Mozilla Science repo uses them for the tutorials, for instance, and this seems to work well.

**Comment by tomhohenstein** [comment]
It sounds like we should setup a coworking session on this to start incorporating submodules. It might also be an opportunity for us to use the wiki to document this workflow. 

I can do before or after the break but I don't want to interfere with the end of the semester fun :anguished: 

-Tom

**Comment by ceholden** [comment]
I'll take a look at this as part of the tasks in #47
