### ISSUE TITLE
3/3 - Docker - STO 442 - 5:00 - 6:30

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#29]
[Reveal.js](http://lab.hakim.se/reveal-js/#/) is a html presentation solution for sharing your work and slides. Learn how to use this great JavaScript library to build clean presentations.

**Comment by tomhohenstein** [comment]
Quick question - since we covered RISE are we still interested in a Reveal.js session?

**Comment by ashiklom** [comment]
Could be worth substituting for something else. Though if we do end up skipping, it might be a good idea for somebody (@ceholden ?) to throw a few links to tutorials up here.

**Comment by ceholden** [comment]
Happy to substitute in another lesson -- maybe the Shiny lesson #35 ?

An argument in favor of keeping this lesson:

The RISE slide show extension is an example of using reveal.js, but knowing how to use RISE doesn't mean you can make a slideshow just using reveal.js. RISE isn't as sharable because it requires Jupyter notebook to be running while a slideshow in pure reveal.js is just a static page to serve.

The official reveal.js docs have you writing HTML encapsulated in the reveal.js code, but I was planning on showing how to make reveal.js presentations using simple Markdown converted to HTML using `pandoc`.

**Comment by tomhohenstein** [comment]
Sounds like a good argument to me. Maybe we can  show how to use reveal.js with a repo to store and present materials.

**Comment by ceholden** [comment]
Great -- I can also make a tie in to the submodule discussion in #26

**Comment by parevalo** [comment]
I also think it would be very useful to keep the reveal.js lesson.

**Comment by tomhohenstein** [comment]
What do we think about having @mattbuechler present on docker on 3/3 and doing the Reveal.js on 3/10?

**Comment by tomhohenstein** [comment]
Sounds like it is best to Docker w/ @mattbuechler on 3/3 and reveal.js w/ @ceholden on 3/17

**Comment by tomhohenstein** [comment]
Hi Everyone, 

Hope you can make tonight's session on Docker! If you're planning on attending, can you give a +1? 

+1

**Comment by ceholden** [comment]
+1 !

**Comment by ashiklom** [comment]
Alas, I can't go -- I'm on dog-sitting duty :dog: :cry:

**Comment by tomhohenstein** [comment]
@ashiklom bring the :dog: !

**Comment by ashiklom** [comment]
Fair point. I actually just walked her so I think she'll be OK staying at work till around 6:30, so count me in!

+1 :+1:

**Comment by wkearn** [comment]
+1

I may need to leave a little early, but I'll be there!

**Comment by tomhohenstein** [comment]
@wkearn no worries. Also, I grabbed the projector

**Comment by tonygardella** [comment]
+1

**Comment by tomhohenstein** [comment]
great session last night - we had 7 attendees
