### ISSUE TITLE
3/17 - Reveal.js - STO 442 - 5:00 - 7:00

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#30]
Makefiles are machine-readable way to document your project's workflow and increase reproducibility. This session will show you how to get started using [Make](https://www.gnu.org/software/make/) with Makefiles.

**Comment by ceholden** [comment]
I've started using Makefiles for some of my data processing workflows, especially when there are expensive intermediate steps that need to be accomplished. I can't say I still don't get frustrated with the syntax and conventions of Makefiles, but I have written a few without being driven to drink.

So +1 for interest and I can volunteer to lead as a last resort!

I'd also like to mention the [Drake](https://github.com/Factual/drake) project that re-invents Makefiles specifically to be tailored for data processing. It looks very powerful and seems from a cursory overview to be closer to shell scripts than a Makefile, but I could be mistaken. One huge draw for me is the ability to create Graphviz-like workflow charts from your "Drakefile". I could go over Drake if I get the chance to use it between now and 3/17.

**Comment by tomhohenstein** [comment]
+1 for this too. I think it would be nice to start with Make and I really like Drake (both as a concept and a tool) too. I'll look into that more.

**Comment by tomhohenstein** [comment]
@ceholden just double checking to make sure you're okay with doing reveal.js on 3/17.

**Comment by ceholden** [comment]
Sure! I might edit this post with more detail later, but for now I'll try to provide a preliminary lesson plan:

I think this topic is best presented as a live demo, but I'll try to bookend the demo with some introduction and leads for further investigation.
- Introduction: who, what, where of `reveal.js`
- Demonstration
  - `git clone https://github.com/hakimel/reveal.js.git`
  - Using HTML slide template, work through some/most of the slide elements in `reveal.js`
  - Using Markdown document and Pandoc for the conversion, translate the slide elements explored in HTML segment to their Markdown equivalents
    - NOTE: This requires `pandoc` be installed on your system
- Further info: links to other HTML based slide show software, shoutout to Jupyter Notebook RISE project, link to web platforms for making HTML slides (e.g., [slides](http://slides.com/))

I think there could be some adjustment in whether we demo fewer features in both HTML and Markdown editing pathways or demo more features in just one of the pathways. I'm leaning toward HTML and Markdown because editing HTML is such a drag, but the HTML pathway does not require Pandoc to be installed so it may be friendlier to some users.

**Comment by tomhohenstein** [comment]
Last minute update that we are meeting in 465 - I'll be posting in a sign in 442

**Comment by tomhohenstein** [comment]
Great session everyone - I counted 9 participants. 

-Tom
