### ISSUE TITLE
20161005 - Jupyter Notebooks

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#62]
Hi Everyone, 

I know it is a few weeks away but does anyone have thoughts about our session for 10/05?

Potential ideas
- Unix
- Git / Github 
- Setting up a Jupyter Notebooks 
- Python - tips and tricks (or Python w/@ceholden) 
- Pros / Cons of different languages (python, r, matlab, etc)

**Comment by wkearn** [comment]
It seems like there has been a fair amount of interest in a pros/cons of different languages session, but I think that's going to be a tricky one to get right (so that it's just not a debate between me, Alexey and Chris). Maybe we shouldn't try to do it in two weeks. 

I'm not sure about interest, but I think Alexey and Betsy really only scratched the surface of Unix and Git this week, and there is a lot more that we could do there. On the other hand, we did also do the Software Carpentry workshops fairly recently.

Other ideas that may have been mentioned in the past
- Make (maybe reproducible builds?)
- Tools for data management (Zenodo, for instance)

**Comment by tomhohenstein** [comment]
@ashiklom @bcow any interest in a git or unix session on 10/5?

**Comment by tomhohenstein** [comment]
Hi Everyone, 

By request, this session will be on Jupyter Notebooks. I'll take the lead for the session but if anyone is interested in helping (or have cool examples) feel free to share.

**Comment by tomhohenstein** [comment]
12 ppl attended.
